"""Utility functions for sharing and copying roasts"""

import hashlib
from datetime import datetime
from typing import Dict


def generate_roast_id(username: str, persona: str) -> str:
    """
    Generate unique ID for a roast session.
    
    Args:
        username: Target username
        persona: Persona used
        
    Returns:
        Unique hash ID
    """
    timestamp = datetime.now().isoformat()
    content = f"{username}_{persona}_{timestamp}"
    return hashlib.md5(content.encode()).hexdigest()[:12]


def format_share_text(roast: str, username: str, persona: str, platform: str = "github") -> str:
    """
    Format roast for sharing (text format).
    
    Args:
        roast: Generated roast text
        username: Target username
        persona: Persona used
        platform: Platform (github, twitter, etc.)
        
    Returns:
        Formatted share text
    """
    share_text = f"""🔥 AI ROAST 🔥
    
Target: @{username} ({platform})
Persona: {persona}

{roast}

---
Generated by AI Roaster MVP
"""
    return share_text.strip()


def format_copy_text(roast: str) -> str:
    """
    Format roast for clipboard (simple format).
    
    Args:
        roast: Generated roast text
        
    Returns:
        Clean roast text for copying
    """
    return roast.strip()


def sanitize_username(username: str) -> str:
    """
    Sanitize username input to prevent injection attacks.
    
    Args:
        username: Raw username input
        
    Returns:
        Sanitized username
    """
    # Remove special characters, keep alphanumeric and basic symbols
    allowed_chars = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_")
    sanitized = "".join(c for c in username if c in allowed_chars)
    return sanitized[:50]  # Max 50 chars


def validate_input(username: str, platform: str) -> tuple[bool, str]:
    """
    Validate user inputs before processing.
    
    Args:
        username: Username to validate
        platform: Platform to validate
        
    Returns:
        Tuple of (is_valid, error_message)
    """
    if not username or len(username.strip()) == 0:
        return False, "Username cannot be empty"
    
    if len(username) > 50:
        return False, "Username too long (max 50 characters)"
    
    sanitized = sanitize_username(username)
    if len(sanitized) == 0:
        return False, "Username contains only invalid characters"
    
    valid_platforms = ["github", "twitter"]
    if platform.lower() not in valid_platforms:
        return False, f"Platform must be one of: {', '.join(valid_platforms)}"
    
    return True, ""


def get_source_snippets(profile_data: Dict) -> str:
    """
    Extract and format source data snippets for transparency.
    
    Args:
        profile_data: Profile data dict from scraper
        
    Returns:
        Formatted source snippets
    """
    snippets = ["### Source Data Used"]
    
    if profile_data.get("bio"):
        bio = profile_data["bio"][:100]
        snippets.append(f"**Bio:** {bio}...")
    
    if profile_data.get("repos"):
        repos = profile_data["repos"][:3]
        snippets.append(f"**Recent Repos:** {', '.join(repos)}")
    
    if profile_data.get("languages"):
        langs = profile_data["languages"][:5]
        snippets.append(f"**Languages Used:** {', '.join(langs)}")
    
    if profile_data.get("recent_activity"):
        activity = profile_data["recent_activity"][:150]
        snippets.append(f"**Recent Activity:** {activity}...")
    
    if len(snippets) == 1:  # Only header
        snippets.append("_No source data available_")
    
    return "\n\n".join(snippets)
